/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DestinationsIdRouteImport } from './routes/destinations.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSendRouteImport } from './routes/admin.send'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as ApiPublicHooksBookingRemindersRouteImport } from './routes/api/public/hooks/booking-reminders'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DestinationsIdRoute = DestinationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DestinationsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSendRoute = AdminSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksBookingRemindersRoute =
  ApiPublicHooksBookingRemindersRouteImport.update({
    id: '/api/public/hooks/booking-reminders',
    path: '/api/public/hooks/booking-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/hotels': typeof HotelsRoute
  '/planner': typeof PlannerRoute
  '/saved': typeof SavedRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/send': typeof AdminSendRoute
  '/admin/users': typeof AdminUsersRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/hotels': typeof HotelsRoute
  '/planner': typeof PlannerRoute
  '/saved': typeof SavedRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/send': typeof AdminSendRoute
  '/admin/users': typeof AdminUsersRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/hotels': typeof HotelsRoute
  '/planner': typeof PlannerRoute
  '/saved': typeof SavedRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/send': typeof AdminSendRoute
  '/admin/users': typeof AdminUsersRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/hooks/booking-reminders': typeof ApiPublicHooksBookingRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/hotels'
    | '/planner'
    | '/saved'
    | '/admin/bookings'
    | '/admin/messages'
    | '/admin/send'
    | '/admin/users'
    | '/destinations/$id'
    | '/admin/'
    | '/api/public/hooks/booking-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/hotels'
    | '/planner'
    | '/saved'
    | '/admin/bookings'
    | '/admin/messages'
    | '/admin/send'
    | '/admin/users'
    | '/destinations/$id'
    | '/admin'
    | '/api/public/hooks/booking-reminders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/destinations'
    | '/hotels'
    | '/planner'
    | '/saved'
    | '/admin/bookings'
    | '/admin/messages'
    | '/admin/send'
    | '/admin/users'
    | '/destinations/$id'
    | '/admin/'
    | '/api/public/hooks/booking-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  HotelsRoute: typeof HotelsRoute
  PlannerRoute: typeof PlannerRoute
  SavedRoute: typeof SavedRoute
  ApiPublicHooksBookingRemindersRoute: typeof ApiPublicHooksBookingRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/destinations/$id': {
      id: '/destinations/$id'
      path: '/$id'
      fullPath: '/destinations/$id'
      preLoaderRoute: typeof DestinationsIdRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/send': {
      id: '/admin/send'
      path: '/send'
      fullPath: '/admin/send'
      preLoaderRoute: typeof AdminSendRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/booking-reminders': {
      id: '/api/public/hooks/booking-reminders'
      path: '/api/public/hooks/booking-reminders'
      fullPath: '/api/public/hooks/booking-reminders'
      preLoaderRoute: typeof ApiPublicHooksBookingRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSendRoute: typeof AdminSendRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSendRoute: AdminSendRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DestinationsRouteChildren {
  DestinationsIdRoute: typeof DestinationsIdRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsIdRoute: DestinationsIdRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  HotelsRoute: HotelsRoute,
  PlannerRoute: PlannerRoute,
  SavedRoute: SavedRoute,
  ApiPublicHooksBookingRemindersRoute: ApiPublicHooksBookingRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
